-- 책 조회
SELECT TBL_BOOK.* FROM TBL_BOOK;

-- 책 컬럼 추가
INSERT INTO TBL_BOOK(BOOK_NAME) VALUES ('단어가 읽기다 기본편');
INSERT INTO TBL_BOOK(BOOK_NAME) VALUES ('단어가 읽기다 실전편');

-- 책 컬럼 삭제 ( ON DELETE CASCADE )
DELETE FROM TBL_BOOK WHERE BOOK_ID = 1;

-- 카테고리 조회
SELECT TBL_CATEGORY.* FROM TBL_CATEGORY;

-- 카테고리 컬럼 추가
INSERT INTO TBL_CATEGORY(CATEGORY_NAME, BOOK_ID) VALUES ('Unit 01 - 요리', 5);
INSERT INTO TBL_CATEGORY(CATEGORY_NAME, BOOK_ID) VALUES ('Unit 01 - 요리', 4); 
INSERT INTO TBL_CATEGORY(CATEGORY_NAME, BOOK_ID) VALUES ('Unit 02 - 일상1', 5);
INSERT INTO TBL_CATEGORY(CATEGORY_NAME, BOOK_ID) VALUES ('Unit 03 - 일상2', 5);

-- 책 테이블과 카테고리 테이블 INNER JOIN
SELECT B.BOOK_ID, B.BOOK_NAME, C.CATEGORY_ID, C.CATEGORY_NAME FROM TBL_BOOK B
INNER JOIN TBL_CATEGORY C ON B.BOOK_ID = C.BOOK_ID;

-- 카테고리 컬럼 삭제 ( ON DELETE CASCADE )
DELETE FROM TBL_CATEGORY WHERE CATEGORY_ID = 6;

-- 단어 조회
SELECT TBL_WORD.* FROM TBL_WORD;

-- 단어 컬럼 추가
INSERT INTO TBL_WORD(WORD_NAME, WORD_MEANING, CATEGORY_ID) VALUES ('spice', '양념', 6);
INSERT INTO TBL_WORD(WORD_NAME, WORD_MEANING, CATEGORY_ID) VALUES ('take', '(수업을)듣다', 6);
INSERT INTO TBL_WORD(WORD_NAME, WORD_MEANING, CATEGORY_ID) VALUES ('take', '(의자에)앉다', 6);
INSERT INTO TBL_WORD(WORD_NAME, WORD_MEANING, CATEGORY_ID) VALUES ('delicious', '맛있는', 6);
INSERT INTO TBL_WORD(WORD_NAME, WORD_MEANING, CATEGORY_ID) VALUES ('tasty', '맛있는', 6);